Repository codesquad-member-2020/dust-5, pull requests merged in 2020-04, with the labels that each got.

#41 [FE] 리뷰 요청 PR
  fe/src/js/dustApp/dustAppController.js
  fe/src/js/dustApp/dustAppEventManager.js
  fe/src/js/dustApp/dustAppModel.js
  fe/src/js/dustApp/dustAppView.js
  fe/src/js/dustForecast/dustForecastEventManager.js
  fe/src/js/dustForecast/dustForecastModel.js
  fe/src/js/dustForecast/dustForecastView
  fe/src/js/dustMenu/dustMenu.js
  fe/src/js/main.js
  fe/webpack.config.js
Labels: FE, FE 리뷰요청

#44 response json에 측정소 이름 추가
  src/main/java/com/example/dust/bean/ApiResponse.java
  src/main/java/com/example/dust/controller/ForecastController.java
Labels: BE

#51 미세먼지 화면 기능 구현 완료
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp/Base.lproj/Main.storyboard
  DustApp/DustApp/Controllers/DustViewController.swift
  DustApp/DustApp/Error/NetworkError.swift
  DustApp/DustApp/Info.plist
  DustApp/DustApp/Model/Coordinate.swift
  DustApp/DustApp/Model/MeasuredHistory.swift
  DustApp/DustApp/Model/State/BadState.swift
  DustApp/DustApp/Model/State/GoodState.swift
  DustApp/DustApp/Model/State/NormalState.swift
  DustApp/DustApp/Model/State/WorstState.swift
  DustApp/DustApp/Network/Dust24NetworkManager.swift
  DustApp/DustApp/Network/EncodeManager.swift
  DustApp/DustApp/Network/LocationManager.swift
  DustApp/DustApp/Network/URLDataTask.swift
  DustApp/DustApp/Protocol/DustState.swift
  DustApp/DustApp/View/Cell/TimelineTableViewCell.swift
  DustApp/DustApp/View/StatusView.swift
  DustApp/DustApp/View/TableView/TimelineTableView.swift
Labels: iOS

#56 예보 화면 데이터 요청
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp/Controllers/ForecastViewController.swift
  DustApp/DustApp/Model/Forecast.swift
  DustApp/DustApp/Network/Dust24NetworkManager.swift
  DustApp/DustApp/Network/ForecastNetworkManager.swift
  DustApp/DustApp/Network/URLDataTask.swift
Labels: iOS

#60 시차 적용
  src/main/java/com/example/dust/DustApplication.java
  src/main/java/com/example/dust/util/ForecastDateUtil.java
Labels: BE

#55 [FE] 예보 탭 기능구현
  fe/.gitignore
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/css/common.css
  fe/src/css/dustApp.css
  fe/src/css/dustForecast.css
  fe/src/js/constants/constant.js
  fe/src/js/constants/url.js
  fe/src/js/dustApp/dustAppController.js
  fe/src/js/dustApp/dustAppEventManager.js
  fe/src/js/dustApp/dustAppModel.js
  fe/src/js/dustApp/dustAppView.js
  fe/src/js/dustForecast/dustForecastController.js
  fe/src/js/dustForecast/dustForecastEventManager.js
  fe/src/js/dustForecast/dustForecastModel.js
  fe/src/js/dustForecast/dustForecastView.js
  fe/src/js/main.js
  fe/src/js/util/commonUtil.js
  fe/webpack.config.js
Labels: FE, FE 리뷰요청

#62 Fe/dev
  fe/.gitignore
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/css/common.css
  fe/src/css/dustApp.css
  fe/src/css/dustForecast.css
  fe/src/js/constants/constant.js
  fe/src/js/constants/url.js
  fe/src/js/dustApp/dustAppController.js
  fe/src/js/dustApp/dustAppEventManager.js
  fe/src/js/dustApp/dustAppModel.js
  fe/src/js/dustApp/dustAppView.js
  fe/src/js/dustForecast/dustForecastController.js
  fe/src/js/dustForecast/dustForecastEventManager.js
  fe/src/js/dustForecast/dustForecastModel.js
  fe/src/js/dustForecast/dustForecastView.js
  fe/src/js/dustMenu/dustMenu.js
  fe/src/js/main.js
  fe/src/js/util/commonUtil.js
  fe/webpack.config.js
Labels: FE

#63 BE 리뷰 요청
  .gitignore
  build.gradle
  src/main/java/com/example/dust/DustApplication.java
  src/main/java/com/example/dust/WebConfig.java
  src/main/java/com/example/dust/bean/ApiResponse.java
  src/main/java/com/example/dust/bean/Coordinate.java
  src/main/java/com/example/dust/bean/CoordinateData.java
  src/main/java/com/example/dust/bean/DustStatus.java
  src/main/java/com/example/dust/bean/DustStatusData.java
  src/main/java/com/example/dust/bean/Forecast.java
  src/main/java/com/example/dust/bean/ForecastData.java
  src/main/java/com/example/dust/bean/Station.java
  src/main/java/com/example/dust/bean/StationData.java
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/exception/BaseException.java
  src/main/java/com/example/dust/exception/CustomAdvice.java
  src/main/java/com/example/dust/message/ErrorMessages.java
  src/main/java/com/example/dust/message/SuccessMessages.java
  src/main/java/com/example/dust/metadata/ApiKey.java
  src/main/java/com/example/dust/metadata/ApiParams.java
  src/main/java/com/example/dust/metadata/ApiUrl.java
  src/main/java/com/example/dust/util/ConnectionUtil.java
  src/main/java/com/example/dust/util/ForecastDateUtil.java
  src/main/java/com/example/dust/util/LocationConverter.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: BE 리뷰 요청
