Repository codesquad-member-2020/dust-5, pull requests merged in 2020-03, with the labels that each got.

#11 탭바 컨트롤러 생성 및 탭바 이미지 변경
  .DS_Store
  .gitignore
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcschemes/xcschememanagement.plist
  DustApp/DustApp/AppDelegate.swift
  DustApp/DustApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  DustApp/DustApp/Assets.xcassets/Contents.json
  DustApp/DustApp/Assets.xcassets/clock.fill.symbolset/Contents.json
  DustApp/DustApp/Assets.xcassets/clock.fill.symbolset/clock.fill.svg
  DustApp/DustApp/Assets.xcassets/smoke.fill.symbolset/Contents.json
  DustApp/DustApp/Assets.xcassets/smoke.fill.symbolset/smoke.fill.svg
  DustApp/DustApp/Base.lproj/LaunchScreen.storyboard
  DustApp/DustApp/Base.lproj/Main.storyboard
  DustApp/DustApp/Info.plist
  DustApp/DustApp/SceneDelegate.swift
  DustApp/DustApp/ViewController.swift
Labels: iOS

#12 미세먼지 화면 기본 ui 생성 및 그라데이션 배경 설정
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp/Base.lproj/Main.storyboard
  DustApp/DustApp/Controllers/DustViewController.swift
  DustApp/DustApp/ViewController.swift
Labels: iOS

#13 예보 화면 기본 ui 구성
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp/Assets.xcassets/arrowtriangle.right.square.symbolset/Contents.json
  DustApp/DustApp/Assets.xcassets/arrowtriangle.right.square.symbolset/arrowtriangle.right.square.svg
  DustApp/DustApp/Base.lproj/Main.storyboard
  DustApp/DustApp/Controllers/DustViewController.swift
  DustApp/DustApp/Controllers/ForecastViewController.swift
Labels: iOS

#18 `미세먼지 앱` 페이지 구현
  .gitignore
  src/main/java/com/example/dust/controller/ForecaseController.java
  src/main/java/com/example/dust/testdata/TestData.java
Labels: BE

#19 미세먼지 앱 화면 html css 작성
  fe/.gitignore
  fe/css/dust.css
  fe/index.html
Labels: FE

#22 feat : pid 파일 생성
  src/main/java/com/example/dust/DustApplication.java
Labels: BE

#25 refactor : `미세먼지 앱` 페이지 구현
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/metadata/ApiKey.java
  src/main/java/com/example/dust/metadata/ApiUrl.java
  src/main/java/com/example/dust/util/UrlBuilder.java
Labels: BE

#32 대기정보에 대한 로직 구체화와 스켈레톤 코드 작성
  .gitignore
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/metadata/ApiKey.java
  src/main/java/com/example/dust/metadata/ApiParams.java
  src/main/java/com/example/dust/metadata/ApiUrl.java
  src/main/java/com/example/dust/util/ConnectionUtil.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: BE

#33 refactor : 결과 수를 늘리기 위한 parameter 추가
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/metadata/ApiParams.java
Labels: BE

#34 #6 미세먼지 화면의 기능 구현
  DustApp/DustApp.xcodeproj/project.pbxproj
  DustApp/DustApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  DustApp/DustApp/Assets.xcassets/bad.imageset/Contents.json
  DustApp/DustApp/Assets.xcassets/bad.imageset/bad.png
  DustApp/DustApp/Assets.xcassets/good.imageset/Contents.json
  DustApp/DustApp/Assets.xcassets/good.imageset/best.png
  DustApp/DustApp/Assets.xcassets/normal.imageset/Contents.json
  DustApp/DustApp/Assets.xcassets/normal.imageset/normal.png
  DustApp/DustApp/Assets.xcassets/worst.imageset/Contents.json
  DustApp/DustApp/Assets.xcassets/worst.imageset/worst.png
  DustApp/DustApp/Base.lproj/Main.storyboard
  DustApp/DustApp/Controllers/DustViewController.swift
  DustApp/DustApp/Model/BadState.swift
  DustApp/DustApp/Model/DustGrade.swift
  DustApp/DustApp/Model/GoodState.swift
  DustApp/DustApp/Model/MeasuredHistory.swift
  DustApp/DustApp/Model/NormalState.swift
  DustApp/DustApp/Model/WorstState.swift
  DustApp/DustApp/Protocol/DustState.swift
  DustApp/DustApp/View/Cell/TimelineTableViewCell.swift
  DustApp/DustApp/View/TableView/TimelineTableView.swift
Labels: iOS

#35 refactor: url 매핑 안되는 함수 다른 class로 이동
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/metadata/ApiParams.java
  src/main/java/com/example/dust/util/LocationConverter.java
Labels: BE

#29 [FE] 미세먼지 탭 화면 기능 구현
  fe/.gitignore
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/css/dustApp.css
  fe/src/js/constants/constant.js
  fe/src/js/controller.js
  fe/src/js/dustApp/dustAppEventManager.js
  fe/src/js/dustApp/dustAppModel.js
  fe/src/js/dustApp/dustAppView.js
  fe/src/js/main.js
  fe/src/js/util/commonUtil.js
  fe/webpack.config.js
Labels: FE, FE 리뷰요청

#36 fe/dev 최신화를 위한 임시 PR
  fe/.gitignore
  fe/src/js/constants/constant.js
  fe/src/js/dustApp/dustAppView.js
Labels: FE

#38 `미세먼지 앱` 구현 완료
  src/main/java/com/example/dust/bean/Coordinate.java
  src/main/java/com/example/dust/bean/CoordinateData.java
  src/main/java/com/example/dust/bean/Station.java
  src/main/java/com/example/dust/bean/StationData.java
  src/main/java/com/example/dust/controller/ForecastController.java
  src/main/java/com/example/dust/util/LocationConverter.java
Labels: BE

#39 [FE] 미세먼지 탭 버그 픽스 + 예보 탭 html 작성
  fe/index.html
  fe/src/css/common.css
  fe/src/css/dustApp.css
  fe/src/css/dustForecast.css
  fe/src/js/controller.js
  fe/src/js/dustApp/dustAppModel.js
  fe/src/js/dustApp/dustAppView.js
Labels: FE
